# Generated by Django 6.1.1 on 2026-09-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='เวลาเริ่มเช็คชื่อ')),
                ('end_time', models.DateTimeField(verbose_name='เวลาสิ้นสุดเช็คชื่อ')),
                ('is_active', models.BooleanField(default=False, verbose_name='เปิดเช็คชื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.course', verbose_name='รายวิชา')),
            ],
        ),
    ]
