# Generated by Django 6.1.1 on 2026-09-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(choices=[(1, 'รอบที่ 1'), (2, 'รอบที่ 2'), (3, 'รอบที่ 3')], verbose_name='รอบ')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP')),
                ('qr_token', models.CharField(max_length=100, unique=True, verbose_name='QR Token')),
                ('valid_from', models.DateTimeField(verbose_name='เริ่มใช้')),
                ('valid_until', models.DateTimeField(verbose_name='หมดอายุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='attendance.attendancesession', verbose_name='การเช็คชื่อ')),
            ],
        ),
    ]
