# Generated by Django 6.1.1 on 2026-09-07 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancetoken_round_number_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_entered', models.CharField(max_length=6, verbose_name='OTP ที่กรอก')),
                ('is_correct', models.BooleanField(default=False, verbose_name='OTP ถูกต้อง')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ส่ง')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to='attendance.attendancesession', verbose_name='การเช็คชื่อ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to=settings.AUTH_USER_MODEL, verbose_name='นักศึกษา')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to='attendance.attendancetoken', verbose_name='Token')),
            ],
        ),
    ]
